# Makefile for arduino-esp32
# See more information at https://github.com/plerup/makeEspArduino

# sketch name is optional
SKETCH := main/Temp.cpp
CHIP   := esp32

BUILD_ROOT = ./build

ESP_ROOT = $(dir ${IDF_PATH})arduino-esp32

include ${ESP_ROOT}/tools/makeEspArduino/makeEspArduino.mk
