# Makefile for arduino-core
# See more information at https://github.com/plerup/makeEspArduino

# sketch name is optional

# Used to test arduino standard libraries & examples
SKETCH := ${ESP_ROOT}/libraries/WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino
CHIP   := esp32

BUILD_ROOT = ./build

ESP_ROOT = ${ESP_PATH}/arduino/arduino-esp32

include ${ESP_PATH}/arduino/makeEspArduino/makeEspArduino.mk