# Used to test arduino standard libraries & examples

ESP_ROOT = ${ESP_PATH}/arduino/arduino-esp32

SKETCH := ${ESP_ROOT}/libraries/WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino
CHIP   := esp32

BUILD_ROOT = ./build


include ${ESP_PATH}/arduino/makeEspArduino/makeEspArduino.mk
