import { type, html, notEmpty, gzip_compress } from '@/utils'

import axios from 'axios'
import { basename, resolve, join } from 'path-browserify'

async function toFormData(data, name = 'data') {
    let filename
    let tmp = data
    let dtype = type(data)
    switch (dtype) {
        case 'file':
            break
        case 'blob':
            break
        case 'object':
            tmp = new Blob([JSON.stringify(tmp)], { type: 'application/json' })
            break
        case 'string':
            filename = basename(name)
            if (filename.endsWith('.gz')) {
                let bytes = await gzip_compress(tmp)
                tmp = new Blob([bytes], { type: 'application/gzip' })
            } else {
                tmp = new Blob([tmp], { type: 'text/plain' })
            }
            break
        case 'uint8array':
        case 'arraybuffer':
            filename = basename(name)
            tmp = new Blob([tmp], { type: 'application/octet-stream' })
            break
        case 'formdata':
            return Promise.resolve(data)
        default:
            return Promise.reject({ message: `Invalid type ${dtype}` })
    }
    data = new FormData()
    data.append(name, tmp, ...(filename ? [filename] : []))
    return Promise.resolve(data)
}

const api = axios.create({
    baseURL: '/api/',
    timeout: 3000,
})

function merge(opt1, opt2, instance = api) {
    return instance(axios.mergeConfig(opt1, opt2))
}

export function getSchema(name = '', opt = {}) {
    return axios.get(resolve('/', `${name ? name + '.' : ''}schema.json`), opt)
}

export function isApmode(opt = {}) {
    return merge(opt, { url: 'apmode' })
}

export function getConfig(opt = {}) {
    return merge(opt, { url: 'config' })
}

export function setConfig(cfg, opt = {}) {
    return merge(opt, {
        url: 'config',
        method: 'POST',
        data: `json=${JSON.stringify(cfg)}`,
    })
}

export function listDir(path = '', opt = {}) {
    return merge(opt, {
        url: 'edit',
        params: { list: path },
    })
}

export function readFile(path, download = false, opt = {}) {
    return merge(opt, {
        url: 'edit',
        responseType: 'text', // raw file: do NOT parse to json
        params: download ? { path, download } : { path },
    })
}

export function createPath(path, isdir = true, opt = {}) {
    return merge(opt, {
        url: 'editc',
        method: 'PUT',
        params: { path, type: isdir ? 'dir' : 'file' },
    })
}
export function deletePath(path, opt = {}) {
    return merge(opt, {
        url: 'editd',
        method: 'DELETE',
        params: { path },
    })
}

export function uploadFile(filename, file, opt = {}) {
    return toFormData(file, filename).then(data =>
        merge(opt, {
            url: 'editu',
            method: 'POST',
            params: { overwrite: '' },
            timeout: 0,
            data,
        })
    )
}

export function updateOTA(firmware, opt = {}) {
    return toFormData(firmware, 'update').then(data =>
        merge(opt, {
            url: 'update',
            method: 'POST',
            timeout: 0,
            data,
        })
    )
}

export function execCommand(cmd, opt = {}) {
    let ctype = type(cmd)
    switch (ctype) {
        case 'string':
            break
        case 'array':
            cmd = cmd.join(' ')
            break
        case 'object':
            cmd = Object.entries(cmd)
                .filter(kv => kv[1])
                .map(kv => kv[0])
                .join(' ')
            break
        default:
            return Promise.reject({ message: `Invalid type ${ctype}` })
    }
    return merge(opt, {
        url: 'cmd',
        method: 'POST',
        data: `exec=${cmd.trim().replace('helpESP', 'help')}`,
    })
}

function parseCommand(str) {
    // An command help generated by argtable3 seems like this:
    //      <name> [<hints> ...]
    //      <desc>
    //          [<args desc>]
    //          [...]
    let lines = str.trim().split('\n')
    let cmd = {
        key: lines[0].split(' ')[0].replace('help', 'helpESP'),
        group: 'server',
        usage: lines[0].trim(),
        description: lines[1].trim(),
    }
    if (lines.length > 3)
        cmd.example = [{ cmd: html(lines.slice(2).join('\n')) }]
    return cmd
}

export function getCommands(opt = {}) {
    return execCommand('help', opt).then(resp => {
        resp.data = resp.data.split('\n\n').filter(notEmpty).map(parseCommand)
        return resp
    })
}
