#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

# final firmware will be ./build/${PROJECT_NAME}.bin
PROJECT_NAME := get-started

include $(IDF_PATH)/make/project.mk
